name: Deploy til sorenpetersen.dk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload via FTP
        run: |
          sudo apt-get install -y lftp
          lftp -e "
            set ftp:passive-mode yes;
            set ssl:verify-certificate no;
            set ftp:ssl-allow yes;
            open -u '${{ secrets.FTP_USERNAME }}','${{ secrets.FTP_PASSWORD }}' linux166.unoeuro.com;
            mirror -R --delete --parallel=4 \
              --exclude .git/ \
              --exclude .github/ \
              . /sorenpetersen.dk/;
            quit
          "
